[package]
name = "ferris-finder"
authors = ["Jenna Fligor <jenna@fligor.net>"]
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "on"

[dependencies]
tui = "0.18.0"
crossterm = "0.23.2"
